spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/local
    username: sa
    password: 12
    driver-class-name: org.h2.Driver

  jpa:
    hibernate.hbm2ddl.auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace